kumuluzee:
  name: property_lease
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/PropertyLeaseDS
      connection-url: jdbc:postgresql://172.17.0.1:33337/property_lease
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://172.17.0.1:2379
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
  cors-filter:
      servlet:
        allow-origin: "*"
  metrics:
        web-instrumentation:
          - name: property_lease-endpoint
            url-pattern: /v1/property_lease/*
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/PropertyLeaseDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="property_lease">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="8452d852-8949-439a-b182-c31a0dd3f805-ls.logit.io" port="17860"
                                                                                         protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'
rest-properties:
  healthy: true