apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: propertyrental-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: propertyrental
    spec:
      containers:
      - image: ggrex/rsobnb-property_rental:0.2
        imagePullPolicy: Always
        name: propertyrental
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://property_rental:8081
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-propertyrental:5432/property_rental
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://168.1.149.41:32623/
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP