apiVersion: v1
kind: Service
metadata:
  name: propertylease
  labels:
    app: propertylease
spec:
  type: NodePort
  ports:
  - name: server
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: propertylease
